### PR TITLE
added swiper with infinite loop and autoplay

### PR DESCRIPTION
**Pull request by dhruv8433**
@Varsani2520 

please check this and merge it

image

- added swiper with auto play, navigation, pagination as  well infinitie loop

### CODE REVIEW

**Comment by Varsani2520** [comment]
project card is cutted

**Comment by dhruv8433** [comment]
@Varsani2520 

is it ok?

image

**Comment by Varsani2520** [comment]
@dhruv8433 ,i want to slider in only responsive screen not a full screen

**Comment by dhruv8433** [comment]
Ok got it @Varsani2520

**Comment by dhruv8433** [comment]
@Varsani2520 

1. Pc screen
image


2. Mobile
image

**Comment by dhruv8433** [comment]
check this and merge it

**Comment by Varsani2520** [comment]
@dhruv8433 ,remove the swiper button

**Comment by Varsani2520** [comment]
i want to only hand touch scroll

**Comment by Varsani2520** [comment]
like this:https://swiperjs.com/demos#scrollbar

**Comment by Varsani2520** [comment]
@dhruv8433 ,ok i do it 
thanks

**Pull request merged**
